
version: 1

models:
    - name: dim_customers
      description: "customer order model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_jaffle_shop__orders
      columns: 
          - name: status
            tests: 
              - accepted_values:
                  values: ['returned','completed','return_pending','shipped','placed']

